name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Unzip project files
        run: unzip CameraAI_FullPackage.zip -d app

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build release APK
        working-directory: app
        run: ./gradlew assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: CameraAI_Release_APK
          path: app/app/build/outputs/apk/release/app-release.apk
